# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/PixelCNNx',
                'doc_host': 'https://Jorgvt.github.io',
                'git_url': 'https://github.com/Jorgvt/PixelCNNx',
                'lib_path': 'PixelCNNx'},
  'syms': {'PixelCNNx.core': {'PixelCNNx.core.foo': ('core.html#foo', 'PixelCNNx/core.py')}}}
